"""123

Revision ID: 2bb947204931
Revises: 
Create Date: 2020-09-16 00:11:41.858144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bb947204931'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_key'), 'config', ['key'], unique=True)
    op.drop_table('sqlite_sequence')
    op.create_index(op.f('ix_user_age'), 'user', ['age'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.drop_index('age', table_name='user')
    op.drop_index('id', table_name='user')
    op.drop_index('name', table_name='user')
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('name', 'user', ['name'], unique=False)
    op.create_index('id', 'user', ['id'], unique=1)
    op.create_index('age', 'user', ['age'], unique=False)
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_age'), table_name='user')
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.drop_index(op.f('ix_config_key'), table_name='config')
    op.drop_table('config')
    # ### end Alembic commands ###
